version: "3.8"
services:
  mho:
    image: matt8100/mho:dev
    container_name: mho
    restart: "unless-stopped"
    environment:
      - NODE_ENV=${NODE_ENV}
      - BOT_TOKEN=${BOT_TOKEN}
  redis:
    image: "redis:alpine"
    container_name: mho_redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf