# Starts bot on production server

name: Continuous Deployment

on:
  workflow_run:
    workflows: [ "Continuous Delivery" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/Mho
          git pull origin main
          npm install --production --package-lock false
          pm2 restart Mho
