# Connects to server by SSH, pull changes, install dependencies and restart

name: Node Continous Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ] 
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/Mho
          git pull origin main
          npm install --production
          pm2 restart Mho
